/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
});
export const ContactLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const Milestone = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});
export const Student = IDL.Record({
  'bio' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'name' : IDL.Text,
  'achievements' : IDL.Vec(IDL.Text),
  'contactLinks' : IDL.Vec(ContactLink),
  'skills' : IDL.Vec(IDL.Text),
  'timeline' : IDL.Vec(Milestone),
});

export const idlService = IDL.Service({
  'getAllStudents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Student))],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Principal], [IDL.Opt(Student)], ['query']),
  'getStudentRecordKey' : IDL.Func([], [IDL.Principal], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
  });
  const ContactLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const Milestone = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  const Student = IDL.Record({
    'bio' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'name' : IDL.Text,
    'achievements' : IDL.Vec(IDL.Text),
    'contactLinks' : IDL.Vec(ContactLink),
    'skills' : IDL.Vec(IDL.Text),
    'timeline' : IDL.Vec(Milestone),
  });
  
  return IDL.Service({
    'getAllStudents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Student))],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Principal], [IDL.Opt(Student)], ['query']),
    'getStudentRecordKey' : IDL.Func([], [IDL.Principal], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };